import { Metadata } from "next";
import "./theme/global.css";

import RootLayout from "./RootLayout";

export const metadata: Metadata = {
  title: "PFR Musical",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
